# Generated by Django 4.1.13 on 2024-05-31 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctor_service.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(2, 'Thứ Hai'), (3, 'Thứ Ba'), (4, 'Thứ Tư'), (5, 'Thứ Năm'), (6, 'Thứ Sáu'), (7, 'Thứ Bảy'), (8, 'Chủ Nhật')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctor_service.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
