# Generated by Django 4.1.13 on 2024-05-30 08:37

import datetime
from django.db import migrations
import djongo.models.fields
import patient_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthinsurance',
            name='id',
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=datetime.datetime(2024, 5, 30, 8, 35, 47, 234972, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='health_insurance',
            field=djongo.models.fields.EmbeddedField(model_container=patient_service.models.HealthInsurance),
        ),
    ]
