# Generated by Django 4.1.13 on 2024-05-30 07:32

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields
import patient_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('medical_history', djongo.models.fields.ArrayField(model_container=patient_service.models.MedicalHistory)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
